# Generated by Django 5.0.6 on 2024-06-23 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_headline_average_rating_headline_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='headline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.headline'),
        ),
    ]
